version: '3'
services:
  php-apache:
    image: webdevops/php-apache-dev
    ports:
      - "8080:80"
      - "4330:443"
      - "9080:9000"
    volumes:
      - "c:\\xampp\\htdocs\\econstruct\\sistema:/var/www/econstruct"
    environment:
      - WEB_DOCUMENT_ROOT=/var/www
    networks:
      - minha-rede
    depends_on:
      - "bd-mysql"

  phpmyadmin:
    image: webdevops/php-apache-dev
    ports:
      - "8081:80"
      - "4331:443"
      - "9081:9000"
    volumes:
      - "c:\\xampp\\phpmyadmin:/var/www/phpmyadmin"
    environment:
      - WEB_DOCUMENT_ROOT=/var/www
    networks:
      - minha-rede
    depends_on:
      - "bd-mysql"

  bd-mysql:
    image: mysql:5.6
    ports:
      - "3380:3306"
    networks:
      - minha-rede
    volumes:
      - "c:\\xampp\\mysql\\data:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

networks:
  minha-rede:
    driver: bridge